//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICI.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class siciEntities2 : DbContext
    {
        public siciEntities2()
            : base("name=siciEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tbl_Anuncios> Tbl_Anuncios { get; set; }
        public virtual DbSet<Tbl_AsistenciaTransferencias> Tbl_AsistenciaTransferencias { get; set; }
        public virtual DbSet<Tbl_Calificaciones> Tbl_Calificaciones { get; set; }
        public virtual DbSet<Tbl_Discapacidades> Tbl_Discapacidades { get; set; }
        public virtual DbSet<Tbl_Especializacion> Tbl_Especializacion { get; set; }
        public virtual DbSet<Tbl_EspecializacionesUsuario> Tbl_EspecializacionesUsuario { get; set; }
        public virtual DbSet<Tbl_Estados> Tbl_Estados { get; set; }
        public virtual DbSet<Tbl_HistoricoNotificaciones> Tbl_HistoricoNotificaciones { get; set; }
        public virtual DbSet<Tbl_Inscripciones> Tbl_Inscripciones { get; set; }
        public virtual DbSet<Tbl_Perfiles> Tbl_Perfiles { get; set; }
        public virtual DbSet<Tbl_Sedes> Tbl_Sedes { get; set; }
        public virtual DbSet<Tbl_Transferencias> Tbl_Transferencias { get; set; }
        public virtual DbSet<Tbl_InformacionBasicaUsuario> Tbl_InformacionBasicaUsuario { get; set; }
        public virtual DbSet<Tbl_ArchivosUsuario> Tbl_ArchivosUsuario { get; set; }
        public virtual DbSet<Tbl_reporteInformacionPorUsuario> Tbl_reporteInformacionPorUsuario { get; set; }
    
        public virtual int PROC_GENERARREPORTE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_GENERARREPORTE");
        }
    
        public virtual int PROC_GENERARREPORTEMVC()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_GENERARREPORTEMVC");
        }
    }
}
