//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICI.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Anuncios
    {
        public int IdAnuncio { get; set; }
        public string AutorAnuncio { get; set; }
        public string TituloAnuncio { get; set; }
        public string DescripcionAnuncio { get; set; }
        public Nullable<System.DateTime> FechaCreacionAnuncio { get; set; }
        public byte[] Imagen { get; set; }
    }
}
