//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICI.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Transferencias
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Transferencias()
        {
            this.Tbl_AsistenciaTransferencias = new HashSet<Tbl_AsistenciaTransferencias>();
            this.Tbl_Calificaciones = new HashSet<Tbl_Calificaciones>();
            this.Tbl_Inscripciones = new HashSet<Tbl_Inscripciones>();
        }
    
        public string NombreTransferencia { get; set; }
        public int IdTransferencia { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> CuposIniciales { get; set; }
        public Nullable<decimal> CuposActuales { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public int EstadoTransferencia { get; set; }
        public int IdEspecializacion { get; set; }
        public int IdSede { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_AsistenciaTransferencias> Tbl_AsistenciaTransferencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Calificaciones> Tbl_Calificaciones { get; set; }
        public virtual Tbl_Especializacion Tbl_Especializacion { get; set; }
        public virtual Tbl_Estados Tbl_Estados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Inscripciones> Tbl_Inscripciones { get; set; }
        public virtual Tbl_Sedes Tbl_Sedes { get; set; }
    }
}
