//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICI.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Sedes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Sedes()
        {
            this.Tbl_AsistenciaTransferencias = new HashSet<Tbl_AsistenciaTransferencias>();
            this.Tbl_Transferencias = new HashSet<Tbl_Transferencias>();
        }
    
        public int IdSede { get; set; }
        public string NombreSede { get; set; }
        public string Direccion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_AsistenciaTransferencias> Tbl_AsistenciaTransferencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Transferencias> Tbl_Transferencias { get; set; }
    }
}
