//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICI.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Discapacidades
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Discapacidades()
        {
            this.Tbl_InformacionBasicaUsuario = new HashSet<Tbl_InformacionBasicaUsuario>();
        }
    
        public int IdDiscapacidad { get; set; }
        public string Descripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_InformacionBasicaUsuario> Tbl_InformacionBasicaUsuario { get; set; }
    }
}
